site_name: JR-GPRS帮助文档
nav:
    - 使用说明: index.md
    - 历史更新: update.md
    - 关于文档: about.md
theme: 
  name: material
  search_index_only: true
  features:
    - navigation.sections
    - navigation.tabs